package ui.web.blink.domain.entities

import com.fasterxml.jackson.annotation.JsonFormat
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.PropertyNamingStrategy
import com.fasterxml.jackson.databind.annotation.JsonNaming
import java.util.*

@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy::class)
@JsonIgnoreProperties(ignoreUnknown = true)
data class Camera(
    val id: Int,
    val name: String,
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ssX")
    val createdAt: Date,
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ssX")
    val updatedAt: Date,
    val status: String,
    val serial: String,
    val fwVersion: String,
    val networkId: Int,
    val type: String,
    val enabled: Boolean,
    val thumbnail: String,
    val battery: String?,
    val usageRate: Boolean,
    val signals: Signal?,
    val cameraKey: String?,
    @JsonProperty("liveview_enabled")
    val liveViewEnabled: String?,
    val sirenEnabled: Boolean?,
    val onboarded: Boolean?,
    val unitNumber: Int?,
    val motionSensitivity: Double?,
    val alertToneEnabled: Boolean?,
    val alertToneVolume: Int?,
    val alertRepeat: String?,
    val alertInterval: Int?,
    val videoLength: Int?,
    val tempAlarmEnable: Boolean?,
    val tempInterval: Int?,
    val tempAdjust: Int?,
    val tempMin: Int?,
    val tempMax: Int?,
    val illuminatiorEnable: Int?,
    val illuminatorDuration: Int?,
    val illuminatorIntensity: Int?,
    val batteryAlarmEnable: Boolean?,
    val batteryVoltageInterval: Int?,
    val batteryVoltageThreshold: Int?,
    val batteryVoltageHysteresis: Int?,
    val batteryAlertCount: Int?,
    val lftSyncInterval: Int?,
    val video5060hz: String?,
    val invertImage: Boolean?,
    val flipImage: Boolean?,
    val recordAudioEnable: Boolean?,
    val clipRate: Int?,
    @JsonProperty("liveview_rate")
    val liveViewRate: Int?,
    val maxResolution: String?,
    val autoTest: Boolean?,
    val wifiTimeout: Int?,
    val retryCount: Int?
    )

/**
"camera": [
{

"wifi_strength": -41,
"lfr_strength": -55,
"temperature": 73,
"battery_voltage": 148,
"a1": false,
"last_temp_alert": null,
"temp_alert_count": 0,
"last_wifi_alert": null,
"wifi_alert_count": 0,
"last_lfr_alert": null,
"lfr_alert_count": 0,
"last_offline_alert": null,
"offline_alert_count": 0,
"temp_alert_state": "in_range",
"battery_state": "ok",
"battery_check_time": "2020-02-14T06:31:09+00:00",
"motion_regions": 33554431,
"mfg_main_type": "EWM",
"mfg_main_range": 1912033705,
"mfg_mez_type": "XWZ",
"mfg_mez_range": 1911337798,
"type": "xt2",
"account_id": 97998,
"network_id": 116468,
"sync_module_id": 207919,
"account": 97998,
"network": 116468,
"camera_seq": 1,
"last_connect": {
"camera_id": 259335,
"created_at": "2020-02-13T10:38:47+00:00",
"updated_at": "2020-02-16T21:18:55+00:00",
"wifi_strength": -49,
"lfr_strength": -56,
"battery_voltage": 148,
"temperature": 73,
"fw_version": "7.96",
"fw_git_hash": "7.95_fixes:b3aec29",
"mac": "f4:b8:5e:8d:65:ff",
"ipv": "ipv4",
"ip_address": "192.168.1.119",
"error_codes": 0,
"battery_alert_status": true,
"temp_alert_status": false,
"ac_power": false,
"light_sensor_ch0": 171,
"light_sensor_ch1": 270,
"light_sensor_data_valid": true,
"light_sensor_data_new": true,
"time_first_video": 111025,
"time_108_boot": 57143,
"time_wlan_connect": 6269128,
"time_dhcp_lease": 6895376,
"time_dns_resolve": 1603,
"lfr_108_wakeups": 40,
"total_108_wakeups": 68,
"lfr_tb_wakeups": 65466,
"total_tb_wakeups": 34816,
"wifi_connect_failure_count": 0,
"dhcp_failure_count": 0,
"socket_failure_count": 6936,
"dev_1": 6901008,
"dev_2": 27,
"dev_3": 458804,
"unit_number": 1,
"serial": "831350271",
"lifetime_count": 0,
"lifetime_duration": 0,
"pir_rejections": 0,
"sync_module_id": 207919,
"network_id": 116468,
"account_id": 97998
},
"motion_alert": true,
"record_audio": true,
"buzzer_on": true,
"early_termination": true,
"clip_bitrate": 2369,
"liveview_bitrate": 0,
"motion_regions_compatible": true,
"early_pir_compatible": false,
"early_notification_compatible": false,
"night_vision_exposure_compatible": false,
"video_quality_support": [
"saver",
"standard",
"best"
],
"video_quality": "best",
"early_notification": false,
"night_vision_exposure": 1,
"clip_max_length": 60,
"early_termination_supported": true,
"clip_warning_threshold": 15
}
],
"signals": {
"lfr": 5,
"wifi": 5,
"updated_at": "2020-02-16T21:18:55+00:00",
"temp": 70,
"battery": 3,
"battery_state": "ok"
}*/